---
title: "Plot Values, SES, NN, and Regression Slopes"
author: "Jon Nations"
date: "4/14/2021"
output: html_document
---

# Fig 4 & S2
Plotting the SES values on the y axis with the nspecies on the x axis. 
2 plots; one for density and one for variance ses.


#Packages and Info
```{r}
pacman::p_load(tidyverse, tidybayes,  modelr, patchwork)
load("Species_Lists.Rdata")
# Rat Color Palette
load("Rat_Colors.Rdata")

level_order <-  c( 'Bawakaraeng', 'Buliohuto','Dako', 'Katopasa',  "Ambang", "Latimojong", 'Torompupu', 'Nokilalaki', "Gandangdewata")
level_order2 <-  c( 'Bawakaraeng', 'Buliohuto',"Dako",'Ambang',  "Latimojong", "Gandangdewata")
```

# Load Data
```{r}
dat <- read_csv("CLEAN_All_Traits.csv") %>% 
  select(-.draw)%>% 
  select(c(com, contains('ses'))) %>% 
  arrange(factor(com, levels = level_order)) %>% 
  mutate(nspec = rep(c(7, 10, 11.9, 12.1, 12.9, 13.1, 15, 17, 23 ), each = 4000)) 


ldat <- read_csv("Locomotion_Data/All_Locomotor_Var.csv") %>%
  arrange(factor(com, levels = level_order)) %>% 
  mutate(nspec=replace(nspec, com == "Katopasa", 12.3),
         nspec=replace(nspec, com == "Dako", 11.7),
         nspec=replace(nspec, com == "Ambang", 12.7),
         nspec=replace(nspec, com == "Latimojong", 13.3))


pdat <- read_csv("Phy_Div/PD_Results.csv")  %>%
  arrange(factor(com, levels = level_order)) %>% 
  mutate(nspec=replace(nspec, com == "Katopasa", 12.3),
         nspec=replace(nspec, com == "Dako", 11.7),
         nspec=replace(nspec, com == "Ambang", 12.7),
         nspec=replace(nspec, com == "Latimojong", 13.3))
# Colors taken from Viridis palette, starting at 0.95 on the yellow side
```

# Plots

## SES Var Combined Traits
```{r}
p1 <- dat %>% 
select(com, nspec, ses_morpho, ses_ext, ses_vBsz, ses_vsk, ses_vIso_group) %>% 
  rename('External Proportions' = ses_ext,
         'Morphology' = ses_morpho,
         'Body Size' = ses_vBsz,
         'Head Shape' = ses_vsk,
         'Isospace' = ses_vIso_group) %>% 
  pivot_longer(!c(com, nspec), 
               names_to = "var") %>% 
  ggplot(aes(y = value, 
             x = nspec, 
             color = var)) +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = 1.64485, 
             linetype = "dotted") +
  geom_hline(yintercept = -1.64485, 
             linetype = "dotted") +
  stat_pointinterval(.width = c(0.74, 0.89), 
                     position = position_dodge(width = 0.8)) +
  labs(x = NULL,
       y = "SES",
       subtitle = "Ecospaces") +
  ylim(-3.1, 3.1) +
  scale_color_manual(values = ratpal, name = "") +
  scale_x_continuous(breaks = c(7, 10, 12, 13, 15, 17, 23)) +
  theme_classic() + 
  theme(legend.justification = "left")
```

## SES Skull
```{r}
p2 <- dat %>% 
select(com, nspec, ses_cv_wei, ses_dv_wei, ses_vdCsize, ses_vcCsize) %>% 
  rename('Cranium Shape' = ses_cv_wei,
         'Dentary Shape' = ses_dv_wei,
         'Cranium Size' = ses_vcCsize,
         'Dentary Size' = ses_vdCsize) %>% 
  pivot_longer(!c(com, nspec), 
               names_to = "var") %>% 
  ggplot(aes(y = value, 
             x = nspec, 
             color = var)) +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = 1.64485, 
             linetype = "dotted") +
  geom_hline(yintercept = -1.64485, 
             linetype = "dotted") +
  stat_pointinterval(.width = c(0.74, 0.89), 
                     position = position_dodge(width = 0.8)) +
  labs(x = NULL,
       y = "SES",
       subtitle = "Skull Traits") +
  ylim(-3.1, 3.1) +
  scale_color_manual(values = ratpal, name = "") +
  scale_x_continuous(breaks = c(7, 10, 12, 13, 15, 17, 23)) +
  theme_classic() + 
  theme(legend.justification = "left")
p2
```

## SES Ext
```{r}
p3 <- dat %>% 
select(com, nspec, ses_vHB, ses_vHF, ses_vTail, ses_vMass, ses_vEar) %>%
  rename('Head-Body Length' = ses_vHB,
         'Tail Length' = ses_vTail,
         'Hind Foot Length' = ses_vHF,
         "Ear Length" = ses_vEar,
         'Mass' = ses_vMass) %>% 
  pivot_longer(!c(com, nspec), 
               names_to = "var") %>% 
  ggplot(aes(y = value, 
             x = nspec, 
             color = var)) +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = 1.64485, 
             linetype = "dotted") +
  geom_hline(yintercept = -1.64485, 
             linetype = "dotted") +
  stat_pointinterval(.width = c(0.74, 0.89), 
                     position = position_dodge(width = 0.8)) +
  labs(x = NULL,
       y = "SES",
       subtitle = "External Measurements") +
  ylim(-3.1, 3.1) +
  scale_color_manual(values = ratpal, name = "") +
  scale_x_continuous(breaks = c(7, 10, 12, 13, 15, 17, 23)) +
  theme_classic() + 
  theme(legend.justification = "left")
p3
```

## SES Iso
```{r}
ldat2 <- ldat %>% select(com, ses_loc_prob)
pdat2 <- pdat %>% select(com, pd_ses)

xLabels <- c("Bawakaraeng (7)", "Buliohuto (10)", "Dako (12)", "Katopasa (12)", "Ambang (13)", "Latimojong (13)", "Torompupu (15)", "Nokilalaki (17)", "Gandang Dewata (23)")


p4 <- dat %>% 
select(com, nspec, ses_vC13_group, ses_vN15_group) %>%
  right_join(ldat2, by = 'com') %>% 
  right_join(pdat2, by = 'com') %>% 
  rename('Nitrogen 15' = ses_vN15_group,
         'Carbon 13' = ses_vC13_group,
         'Locomotor Mode' = ses_loc_prob,
         'Phylogenetic Diversity' = pd_ses) %>% 
  pivot_longer(!c(com, nspec), 
               names_to = "var") %>% 
    mutate(var = factor(var, levels = c("Nitrogen 15", "Carbon 13","Locomotor Mode", "Phylogenetic Diversity"))) %>% 
  ggplot(aes(y = value, 
             x = nspec, 
             color = var)) +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = 1.64485, 
             linetype = "dotted") +
  geom_hline(yintercept = -1.64485, 
             linetype = "dotted") +
  stat_pointinterval(.width = c(0.74, 0.89), 
                     position = position_dodge(width = 0.8)) +
  labs(x = "Species Richness",
       y = "SES",
       subtitle = "Isospace, Locomotor & Phylogenetic Diversity") +
  ylim(-3.1, 3.1) +
  scale_color_manual(values = ratpal, name = "") +
  scale_x_continuous(breaks = c(7, 10, 11.77 ,12.23, 12.77,13.23, 15, 17, 23),
                     labels = xLabels) +
  theme_classic() + 
  theme(legend.justification = "left",
        axis.text.x = element_text(angle = -50, vjust = 1, hjust = 0, size = 8))#, vjust = -1))
p4 
```

# SES ALL
```{r}
p1 / p2 / p3 / p4 #+ plot_layout(guides = 'collect')

```

## NNSES Var Combined
```{r}
n1 <- dat %>% 
select(com, nspec, nnses_morpho, nnses_ext, nnses_Bsz, nnses_sk, nnses_iso_group) %>% 
  rename('External Proportions' = nnses_ext,
         'Morphology' = nnses_morpho,
         'Body Size' = nnses_Bsz,
         'Head Shape' = nnses_sk,
         'Isospace' = nnses_iso_group) %>% 
  pivot_longer(!c(com, nspec), 
               names_to = "var") %>% 
  ggplot(aes(y = value, 
             x = nspec, 
             color = var)) +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = 1.64485, 
             linetype = "dotted") +
  geom_hline(yintercept = -1.64485, 
             linetype = "dotted") +
  stat_pointinterval(.width = c(0.74, 0.89), 
                     position = position_dodge(width = 0.8)) +
  labs(x = NULL,
       y = "Nearest Neighbor SES",
       subtitle = "Ecospace Densities") +
  ylim(-3.1, 3.1) +
  scale_color_manual(values = ratpal, name = "") +
  scale_x_continuous(breaks = c(7, 10, 12, 13, 15, 17, 23)) +
  theme_classic() + 
  theme(legend.justification = "left")
n1
```

## NNSES Cranial
```{r}
n2 <- dat %>% 
select(com, nspec, nnses_c, nnses_d, nnses_csize, nnses_dsize) %>% 
  rename('Cranium Shape' = nnses_c,
         'Dentary Shape' = nnses_d,
         'Cranium Size' = nnses_csize,
         'Dentary Size' = nnses_dsize) %>% 
  pivot_longer(!c(com, nspec), 
               names_to = "var") %>% 
  ggplot(aes(y = value, 
             x = nspec, 
             color = var)) +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = 1.64485, 
             linetype = "dotted") +
  geom_hline(yintercept = -1.64485, 
             linetype = "dotted") +
  stat_pointinterval(.width = c( 0.74, 0.89), 
                     position = position_dodge(width = 0.8)) +
  labs(x = NULL,
       y = "Nearest Neighbor SES",
       subtitle = "Skull Trait Densities") +
  ylim(-3.1, 3.1) +
  scale_color_manual(values = ratpal, name = "") +
  scale_x_continuous(breaks = c(7, 10, 12, 13, 15, 17, 23)) +
  theme_classic() + 
  theme(legend.justification = "left")
n2
```

## NNSES EXT
```{r}
n3 <- dat %>% 
select(com, nspec, nnses_HB, nnses_HF, nnses_Tail, nnses_Mass, nnses_Ear) %>%
  rename('Head-Body Length' = nnses_HB,
         'Tail Length' = nnses_Tail,
         'Hind Foot Length' = nnses_HF,
         "Ear Length" = nnses_Ear,
         'Mass' = nnses_Mass) %>% 
  pivot_longer(!c(com, nspec), 
               names_to = "var") %>% 
  ggplot(aes(y = value, 
             x = nspec, 
             color = var)) +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = 1.64485, 
             linetype = "dotted") +
  geom_hline(yintercept = -1.64485, 
             linetype = "dotted") +
  stat_pointinterval(.width = c(0.74, 0.89), 
                     position = position_dodge(width = 0.8)) +
  labs(x = NULL,
       y = "Nearest Neighbor SES",
       subtitle = "External Measurement Densities") +
  ylim(-3.1, 3.1) +
  scale_color_manual(values = ratpal, name = "") +
  scale_x_continuous(breaks = c(7, 10, 12, 13, 15, 17, 23)) +
  theme_classic() + 
  theme(legend.justification = "left")
n3
```

## NNSES ISO
```{r}
ldat2 <- ldat %>% select(com, nnses_loc)


n4 <- dat %>% 
select(com, nspec, nnses_C13_group, nnses_N15_group) %>%
  right_join(ldat2, by = 'com') %>%
  rename('Nitrogen 15' = nnses_N15_group,
         'Carbon 13' = nnses_C13_group,
         'Locomotor Mode' = nnses_loc) %>% 
  pivot_longer(!c(com, nspec), 
               names_to = "var") %>% 
  mutate(var = factor(var, levels = c("Nitrogen 15", "Carbon 13","Locomotor Mode"))) %>% 
  ggplot(aes(y = value, 
             x = nspec, 
             color = var)) +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = 1.64485, 
             linetype = "dotted") +
  geom_hline(yintercept = -1.64485, 
             linetype = "dotted") +
  stat_pointinterval(.width = c( 0.74, 0.89), 
                     position = position_dodge(width = 0.8)) +
  labs(x = "Species Richness",
       y = "Nearest Neighbor SES",
       subtitle = "Isospace & Locomotor Densities") +
  ylim(-3.1, 4.21) +
  scale_color_manual(values = ratpal, name = "") +
  scale_x_continuous(breaks = c(7, 10, 11.77 ,12.23, 12.77,13.23, 15, 17, 23),
                     labels = xLabels) +
  theme_classic() + 
  theme(legend.justification = "left",
        axis.text.x = element_text(angle = -50, vjust = 1, hjust = 0, size = 7.7, face = "bold"))
n4 
```

# NNSES All
```{r}
(n1 + n2) / (n3 + n4) #+ plot_layout(guides = 'collect')

```


# Plot ALL
```{r}
try1 <- p1 + n1 + plot_layout(guides = "collect")

try2 <- p2 + n2 + plot_layout(guides = "collect")

try3 <- p3 + n3 + plot_layout(guides = "collect")

try4 <- p4 + n4 + plot_layout(guides = "collect")
```

```{r}
try1 / try2 / try3 / try4 + plot_layout(tag_level = 'new') + plot_annotation(tag_levels = list(c('A', '', 'B', '', 'C', '', 'D', '')))

ggsave(file = "Ecospace_Richness_Plots.pdf", height = 8, width = 11)
```

# Variance Plots
```{r}
(p1 + p2) / (p3 + p4) + plot_layout(tag_level = 'new') +
  plot_annotation(tag_levels = list(c('A', 'B', 'C', 'D')))
  

#ggsave(file = "Variance_Richness_Plots.pdf", height = 7, width = 14)
```

#### Variance Plots Vertical
```{r}
p1 / p2 / p3 / p4 + plot_layout(tag_level = 'new') +
  plot_annotation(tag_levels = list(c('A', 'B', 'C', 'D')))
  

ggsave(file = "Plots/Fig4_Variance_Richness_Plots_Vertical-com_labels.pdf", height = 11, width = 7.5)
ggsave(file = "Plots/Fig4_Variance_Richness_Plots_Vertical-com_labels.png", height = 11, width = 7.5)
```

# Density Plots
```{r}
(n1 + n2) / (n3 + n4) + plot_layout(tag_level = 'new') +
  plot_annotation(tag_levels = list(c('A', 'B', 'C', 'D')))
  

#ggsave(file = "Plots/Fig4_Density_Richness_Plots.pdf", height = 7, width = 14)
```

```{r}
n1 / n2 / n3 / n4 + plot_layout(tag_level = 'new') +
  plot_annotation(tag_levels = list(c('A', 'B', 'C', 'D')))
  

ggsave(file = "Plots/FigS2_Density_Richness_Plots_vertical-com_labels.pdf", height = 10, width = 7.5)
```

